### ISSUE TITLE
Insufficient fund with Ocean pacific dataset registration

### ISSUE THREAD

**Issue by areaboy** [oceanprotocol/react-tutorial#7]
I configured the code to use Ocean Pacific Protocol. Now when I tried to register data assets from ocean pacific, it throws error **insufficient fund** at metamask browser. please what do I do. Thanks

**Comment by kremalicious** [comment]
If you have read the react tutorial you also know about the ETH requirement since every transaction costs gas. https://docs.oceanprotocol.com/tutorials/react-setup/#requirements

In the same section you find a tutorial on how to get ETH for Pacific https://docs.oceanprotocol.com/tutorials/get-ether-and-ocean-tokens/#get-ether-for-the-pacific-network
